### PR TITLE
fixbug: https://github.com/quilljs/parchment/issues/26

### PR DESCRIPTION
**Pull request by tester1-for-test-cli**
details in https://github.com/quilljs/parchment/issues/26

@jhchen I don't know why my last account(coder2-seekforwings) can NOT sign in 'travis-ci.org' successfully, so I have to open a pull request again

### CODE REVIEW

**Comment by tester1-for-test-cli** [comment]
https://travis-ci.org/quilljs/parchment/builds/221559724
@jhchen build failed, can you please have a look at it?

**Comment by jhchen** [comment]
Don't worry about the test. The issue is this seems to prevent legitimate moves of sibling elements.

What is the root cause of the bug this PR tries to fix?

**Comment by tester1-for-test-cli** [comment]
http://jsrun.net/CEkKp/edit
Above is a test demo for the Node.insertBefore method. And we can see that inserting the same child will make the current range changes in some new webbrowsers. The project 'parchment' does the same thing like this above, and will cause logical error! And we've already tested that inserting the same child will not make any changes of the dom tree. So I think the best way to fix the problem is to avoid unnecessary insert action.
In a word, the root cause of the bug is that in new some webbrowsers inserting the same child make the range changs. For the reason that I can't read any codes of the those webbrowsers, I can't precisely tell you where goes wrong. I can only tried like the test demo above.

**Comment by tester1-for-test-cli** [comment]
@jhchen Yes you're right. If I do so, some refNodes may not be well be sorted. But I tried again, if we do need to sorted the refNode and childNodes under the parent node. In some new webbrowsers still have the same problem!. This is some kind of holy shit :(

**Comment by tester1-for-test-cli** [comment]
@jhchen I think we may have to check the selection.composing. If it is composing, it means we should not yet insert any node. What about it?

**Comment by coder2-seekforwings** [comment]
@jhchen What's up? Why no answer? Don't you think the problem serious? Can't you have any response? I've been waiting for your answer for 3 days as you see.

**Comment by tester1-for-test-cli** [comment]
@jhchen could you please say anything? I've been waiting for you for 5 days

**Comment by jhchen** [comment]
This PR regresses main normal functionality so it cannot be accepted as it. My suggestion is to dig into the root cause to design a solution rather than guess and try.

**Comment by coder3-seekforwings** [comment]
@jhchen Well, I am willing to dig deeper into the root cause. The question is that: 1. I have no idea how to check if it is really the cause of the web browser. 2. I have my own job working on, now I did the work like what I said before(check if it is composition input, and avoid ‘Node.insertBefore‘), by overriding method 'insertInto' in these blots(Block/Container/Break/Text/Embed), and this is what I can do! I will be very happy if you can offer some little help! By the way, I've been developing as a front-end developer for no more than 1 year. I am not a developer with much experience. So I can only do what I can think. And the thing in this link(https://github.com/quilljs/parchment/issues/26) took me 2 days on tracking the cause. It made me kind of tired! However, I finally found the very detail, which made me feel good, because I think it would be very helpful for fixing the problem. I think this similar demo can help you understand the problem: http://jsrun.net/CEkKp/edit

And one more thing! I registered 4 accounts, and 3 accounts was unable to commit any thing in your project, and I have no idea what's wrong. Please don't do so, I am really trying to fix the problems together! If I did something wrong, just tell me please. I don't want to register any accounts anymore. It has no fun at all.

**Comment by jhchen** [comment]
I'm not accepting buggy code and now that I know you are all the same person you are being blocked for intentional spam.

**Pull request closed without merging**
