### PR TITLE
Replace interface Blot and Parent with actual class as a type

### LINKED ISSUE #53: Type definitions could be cleaner if the Blot and BlotConstructor interface were removed
I've been trying to improve the type definitions for Quill and have been running into this issue lately. There are quite a few places where something is typed as being `Blot` (from the interface) or `BlotConstructor` (an interface with `new(): Blot`). The largest issue with the Blot/BlotConstructor interface is that it requires defining static and instance properties/methods in different places. Instead you should be able to use the base Blot class `ShadowBlot` as a class, and where you need its constructor use `typeof ShadowBlot`.

### PR DESCRIPTION
**Pull request by charrondev**
Closes #53 

Having Blot and Parent as an interface meant constantly fighting with anything that returned `Blot` or `Parent`. In particular it made working with children a pain especially if you needed to access any of its static properties (typescript interfaces can't define static properties).

This PR removes interfaces with only a single implementation in favour of using that implementation as a type. Additionally the `BlotConstructor` type is no defined as `typeof Blot` so that all static properties are now hinting without having to be redefined.

`Formattable` did have multiple different implementations though, so I left it as an interface in `formattable.ts`.

In this case I did rename `ShadowBlot` to `Blot` in order to not have to many of areas where `Blot` is used as a type. If you want to keep `ShadowBlot` as the name I can go in and change those though.

### CODE REVIEW

**Comment by charrondev** [comment]
Hmm. There seems to be an issue with the SauceLabs CI test.

```sh
The environment you requested was unavailable.
  Sauce Labs Authentication Error.
You used username 'None' and access key 'None' to authenticate, which are not valid Sauce Labs credentials.
```

**Comment by jhchen** [comment]
Thanks for the interest in contributing to Parchment. It would be more helpful to start with something smaller. The current API has been carefully thought out and so any changes / proposals also need to be equally carefully evaluated and a PR of this length (almost 500 lines changed) makes this particularly onerous.

**Comment by charrondev** [comment]
If there is something smaller you'd like to contribute I'd be happy to take a look at it. This on only seems a bit large because of the renaming or ShadowBlot to Blot. Would you rather I remove it from this PR? It would reduce the lines changed by a good amount.

**Comment by jhchen** [comment]
No the change from an interface to a class is a big change as it is fundamental. The lines are another thing I would have to audit to make sure there were no errors but tools can help with that. The main issue is this seems to have unknown benefit -- as a user and developer on Parchment -- and I will not have time to reevaluate before 2.0 is out.

**Comment by charrondev** [comment]
The benefit is not having to maintain an interface that is only ever implemented a single way. Unless a you have intentions of having something else implement Blot, that does not extend from ShadowBlot.

The primary (and relatively minor) issue with returning the Blot interface and the class implementation is that every property of the class needs to be synced back to the interface if you use it somewhere otherwise someone downwind using typescript will have to cast variables to ShadowBlot or some other Blot blot class type everytime they need to use a property that isn't synced up between the interface and the class.

**Pull request closed without merging**
